# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup dependencies
        run: |
          sudo apt-get install -y gcc-13 libtbb2-dev
          sudo update-alternatives \
          --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 \
          --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-13 \
          --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-13 \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-13
        shell: bash
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
           cd /home/runner/work/AoC2023/AoC2023
           chmod +x ./buildall.sh
           ./buildall.sh
        shell: bash
